title: The Datahub
email: matthias.vandermaesen@vlaamsekunstcollectie.be
description: >- # this means to ignore newlines until "baseurl:"
  Project website for The Datahub project
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

#########################
# Plugin: jekyll-assets #
#########################

# Assets Pipeline
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

  # Disable asset gzip
  gzip: false

