title: The Datahub
email: matthias.vandermaesen@vlaamsekunstcollectie.be
description: >- # this means to ignore newlines until "baseurl:"
  Project website for The Datahub project
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
