title: The Datahub
email: matthias.vandermaesen@vlaamsekunstcollectie.be
description: >- # this means to ignore newlines until "baseurl:"
  Project website for The Datahub project
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed